name: gigd-devops-github-action
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    # installer les dépendances
    - name: Install and build
      run: npm install && npm run build
    # les test unitaire
    - name: run unit test
      run: npm run test
